In [7]:
import torch
import numpy as np

In [3]:
v = torch.tensor([1,2,3,4,5,6])
print(v[1:4])

tensor([2, 3, 4])


In [5]:
f = torch.FloatTensor([1,2,3,4,5,6])
print(f.size())

torch.Size([6])


In [6]:
v.view(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [8]:
a = np.array([1,2,3,4,5])
tensor_cnv = torch.from_numpy(a)

In [9]:
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5], dtype=torch.int32)
torch.IntTensor
